export const LOAD_MODEL_PATH = "LOAD_MODEL_PATH";
export const LOAD_MODEL_PATH_SUCCESS = "LOAD_MODEL_PATH_SUCCESS";
export const GET_REQUEST_ID_SUCCESS = "GET_REQUEST_ID_SUCCESS";
export const GET_REQUEST_METHOD_SUCCESS = "GET_REQUEST_METHOD_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
