export const LOAD_MODEL_PATH = "LOAD_MODEL_PATH";
export const LOAD_MODEL_PATH_SUCCESS = "LOAD_MODEL_PATH_SUCCESS";

export const GET_REQUEST_ID_SUCCESS = "GET_REQUEST_ID_SUCCESS";
export const GET_REQUEST_METHOD_SUCCESS = "GET_REQUEST_METHOD_SUCCESS";
export const GET_REQUEST_CONTENT_SUCCESS = "GET_REQUEST_CONTENT_SUCCESS";

export const GET_RESPONSE_METHOD_SUCCESS = "GET_RESPONSE_METHOD_SUCCESS";
export const GET_RESPONSE_KEYS_SUCCESS = "GET_RESPONSE_KEYS_SUCCESS";
export const GET_RETURN_METHOD_SUCCESS = "GET_RETURN_METHOD_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const GET_UPDATE_FROM_MODEL = "GET_UPDATE_FROM_MODEL";
export const WAIT_FOR_UPDATE = "WAIT_FOR_UPDATE";
